name: Flask application deployment on EC2 and publish to Ghcr

on:
  push:
    branches:
      - main

jobs:
  # checkout repo ----> login in to ghcr ---> build our dockerfile ---> push it to ghcr     
  build_and_push:
     name: Build image and push
     runs-on: ubuntu-24.04
     permissions:
       contents: read
       packages: write

     steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building our flask application Dockerfile
        run: docker build -t ghcr.io/${{ github.repository_owner }}/flask-image:latest .

      - name: Pushing flask application to Ghcr
        run: docker push ghcr.io/${{ github.repository_owner }}/flask-image:latest
